[package]
edition = "2021"
name = "test-client"
version = "0.1.0"

[dependencies]
anyhow = "1.0.66"
clap = {version = "4.0.18", features = ["derive"]}
image = "0.24.5"
shlex = "1.1.0"
stable-diffusion-a1111-webui-client = {path = "../"}
tokio = {version = "1.21.2", features = ["full"]}
